### ISSUE TITLE
Account key is invalid

### ISSUE THREAD

**Issue by figericnewton** [ten7/computing-for-covid#1]
The account key setup by the onboot script is not valid

https://github.com/ten7/computing-for-covid/blob/ac4dc6f0786af87f6521ec6ee2cc0b769fe9f31f/packer/files/var/lib/cloud/scripts/per-instance/001_onboot#L11

This causes the droplet to spin up, attach to the project, but not actually begin doing work. To fix droplets that are already created, run
```
/usr/bin/boinccmd --project https://boinc.bakerlab.org/rosetta detach
/usr/bin/boinccmd --project_attach https://boinc.bakerlab.org/rosetta CORRECTED_ACCOUNT_KEY
```

feel free to use the weak key on the boinc account I just created (2158663_6bde77eac40091d5dd79178212f46820), or go double check what yours is

**Comment by ivanstegic** [comment]
@figericnewton thank you so much for this, and apologies for not responding any sooner. This was actually fixed in the v2 image, but I just pushed new code for an updated image (v3) and I doubled checked the weak key and it seems to be correct now. Thanks for contributing.
